### ISSUE TITLE
Improve exception handling regarding source attachments

### ISSUE THREAD

**Issue by vbergmann** [AludraTest/aludratest#24]
Technical exceptions imply a framework issue, thus are logged without screenshot or page source attachment. But there are cases in which a technical exception is the test programmer's fault and should be recognized and reported this way, including the screenshot and page source. 

Example:

``` text
com.thoughtworks.selenium.SeleniumException: ERROR: Element css=[id$=":hld_pg"] is not a toggle-button.
at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:109)
at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:103)
at com.thoughtworks.selenium.HttpCommandProcessor.getString(HttpCommandProcessor.java:272)
at com.thoughtworks.selenium.HttpCommandProcessor.getBoolean(HttpCommandProcessor.java:345)
at com.thoughtworks.selenium.DefaultSelenium.isChecked(DefaultSelenium.java:483)
at org.aludratest.service.gui.web.selenium.selenium1.SeleniumFacade.isChecked(SeleniumFacade.java:339)
at org.aludratest.service.gui.web.selenium.selenium1.SeleniumWrapper$14.call(SeleniumWrapper.java:404)
at org.aludratest.service.gui.web.selenium.selenium1.SeleniumWrapper$14.call(SeleniumWrapper.java:401)
at org.aludratest.service.gui.web.selenium.selenium1.SeleniumWrapper.callElementCommand(SeleniumWrapper.java:712)
at org.aludratest.service.gui.web.selenium.selenium1.SeleniumWrapper.isChecked(SeleniumWrapper.java:407)
at org.aludratest.service.gui.web.selenium.selenium1.Selenium1Interaction.selectCheckbox(Selenium1Interaction.java:61)
...
```

Here the programmer has specified a locator for a web GUI element of the wrong type and the web page source attachment would significantly simplify the examination of the fault.

Unfortunately Selenium uses one single exception class (SeleniumException) for any kind of issue. For such cases it looks like an exception mapper would have to rely on the text format of the message (which would make possibly fail with future versions of Selenium) and individual knowledge of the context in which the exception occurred (which would make little generic).

**Comment by falbrech-hsdg** [comment]
Closing as WONTFIX, as similar functionality is now available via global configuration.
