### ISSUE TITLE
WebGuiService: No PerformanceException thrown for failed login

### ISSUE THREAD

**Issue by pbrinkho-hsdg** [AludraTest/aludratest#7]
After a login timed out (exceeding timout of 45000ms set in seleniumWrapper.properties) an UndeclaredThrowableException is thrown. Regarding this the restart of the testcase is not performed. 

Expected: 
*PerformanceException is thrown
*Retry mechanism restarts execution of testcase as configured in "retry.properties"

*Current situation: 
** UndeclaredThrowableException is thrown (see below)
** Testcase is stopped and marked as Framework exception in log 

StackTrace:
```
java.lang.reflect.UndeclaredThrowableException at $Proxy34.open(Unknown Source) at
com.***.LoginPage.openLoginPage(LoginPage.java:128) at com.***.LoginPage.as(LoginPage.java:41) at
com.***..testID(***.java:60) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) at
java.lang.reflect.Method.invoke(Method.java:597) at
org.aludratest.invoker.AludraTestMethodInvoker.invoke(AludraTestMethodInvoker.java:77) at
org.aludratest.scheduler.impl.AludraTestRunnerImpl$RunnerLeafRunnable.call(AludraTestRunnerImpl.java:365) at
org.aludratest.scheduler.impl.AludraTestRunnerImpl$RunnerLeafRunnable.call(AludraTestRunnerImpl.java:311) at
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) at
java.util.concurrent.FutureTask.run(FutureTask.java:138) at
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.reflect.InvocationTargetException at sun.reflect.GeneratedMethodAccessor582.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) at
java.lang.reflect.Method.invoke(Method.java:597) at
org.aludratest.service.impl.AludraServiceInvocationHandler.invoke(AludraServiceInvocationHandler.java:80) ... 16 more
Caused by: org.aludratest.exception.PerformanceFailure: Error opening 'http://***/' :
com.thoughtworks.selenium.SeleniumException: Timed out after 45000ms at
org.aludratest.service.gui.web.selenium.selenium1.SeleniumFacade.open(SeleniumFacade.java:180) at
org.aludratest.service.gui.web.selenium.selenium1.SeleniumWrapper.open(SeleniumWrapper.java:138) at
org.aludratest.service.gui.web.selenium.selenium1.Selenium1Interaction.open(Selenium1Interaction.java:162) at
org.aludratest.service.gui.web.selenium.selenium1.AludraSelenium1.open(AludraSelenium1.java:103) ... 20 more
```

**Comment by pbrinkho-hsdg** [comment]
Sucessfully retested.
